### ISSUE TITLE
Compilation Error "cannot deduce template arguments for 'plus' from ()"

### ISSUE THREAD

**Issue by brytsknguyen** [SplineLib/SplineLib#1] opened 2021-06-28 07:25 UTC
Hi,

I was calling `spack install splinelib` and got the error mentioned above.
My cmake version is 3.20.5. OS is ubuntu 18.04.

The terminal output is given below.

Looking forward to your help!

```
==> Warning: Missing a source id for splinelib@main
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/pkgconf-1.7.4-ttgrqz5oz2wi5qzsvwz2tfp4hyjheqz4
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/berkeley-db-18.1.40-bzu2dnn7kbq5dvg2655uhfbf4bhegesh
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/zlib-1.2.11-xz7vmkd54yh54wvnhf7o4fjft6h6f2rv
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/ncurses-6.2-cb3ymgre5j7oeyapmuiwq2bll46vunzr
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/readline-8.1-e2wukszqrdu47fgvpysj474paxbtuike
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/gdbm-1.19-njwjlsnp6g6bh4j2jpqcza6kjnbzwgdk
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/perl-5.34.0-t5taun5tz5bwydoubev4vwmzjsqhldxj
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/openssl-1.1.1k-utjbo6p7n4gqu7tnmdtpsdienh7cbbe7
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cmake-3.20.3-kosogc56ba43noad25wrnzx7warvkocu
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/pugixml-1.11.4-rcvtmxgtx5twto2awrlzyrgfbew4taoa
[+] /home/tmn/Libraries/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/googletest-1.10.0-hq4orc3exdizu4z45gmrnw54gf7pbzo5
==> Installing splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75
==> No binary for splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75 found: installing from source
==> Warning: Missing a source id for splinelib@main
==> No patches needed for splinelib
==> splinelib: Executing phase: 'cmake'
==> splinelib: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

8 errors found in build log:
     41    cd /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-build-xwh3dhv/Sources/Utilities && /home/tmn/Lib
           raries/spack/lib/spack/env/gcc/g++ -Dutilities_EXPORTS -I/tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/
           spack-src -O2 -g -DNDEBUG -fPIC -O3 -march=native -Wall -Wextra -Wpedantic -Wzero-as-null-pointer-constant -Wno-unused -std=gnu++2a -MD -M
           T Sources/Utilities/CMakeFiles/utilities.dir/math_operations.cpp.o -MF CMakeFiles/utilities.dir/math_operations.cpp.o.d -o CMakeFiles/util
           ities.dir/math_operations.cpp.o -c /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Util
           ities/math_operations.cpp
     42    cd /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-build-xwh3dhv/Sources/Utilities && /home/tmn/Lib
           raries/spack/lib/spack/env/gcc/g++ -Dutilities_EXPORTS -I/tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/
           spack-src -O2 -g -DNDEBUG -fPIC -O3 -march=native -Wall -Wextra -Wpedantic -Wzero-as-null-pointer-constant -Wno-unused -std=gnu++2a -MD -M
           T Sources/Utilities/CMakeFiles/utilities.dir/string_operations.cpp.o -MF CMakeFiles/utilities.dir/string_operations.cpp.o.d -o CMakeFiles/
           utilities.dir/string_operations.cpp.o -c /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Source
           s/Utilities/string_operations.cpp
     43    In file included from /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_con
           tainer_operations.hpp:124,
     44                     from /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/string_
           operations.hpp:33,
     45                     from /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/string_
           operations.cpp:16:
     46    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
            In function 'constexpr ContainerType& splinelib::sources::utilities::std_container_operations::AddAndAssignToFirst(ContainerType&, const 
           ContainerType&)':
  >> 47    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
           114:78: error: cannot deduce template arguments for 'plus' from ()
     48       std::transform(lhs.begin(), lhs.end(), rhs.begin(), lhs.begin(), std::plus());
     49                                                                                  ^
     50    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
            In function 'constexpr ContainerType& splinelib::sources::utilities::std_container_operations::SubtractAndAssignToFirst(ContainerType&, c
           onst ContainerType&)':
  >> 51    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
           148:79: error: cannot deduce template arguments for 'minus' from ()
     52       std::transform(lhs.begin(), lhs.end(), rhs.begin(), lhs.begin(), std::minus());
     53                                                                                   ^
     54    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
            In function 'constexpr ContainerType splinelib::sources::utilities::std_container_operations::Multiply(const ContainerType&, const typena
           me ContainerType::value_type::Type_&)':
  >> 55    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
           179:87: error: cannot deduce template arguments for 'multiplies' from ()
     56         transform(container.begin(), container.end(), multiplied.begin(), bind(multiplies(), _1, factor));
     57                                                                                           ^
  >> 58    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
           182:99: error: cannot deduce template arguments for 'multiplies' from ()
     59         transform(container.begin(), container.end(), std::back_inserter(multiplied), bind(multiplies(), _1, factor));
     60                                                                                                       ^
     61    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
            In function 'ContainerType& splinelib::sources::utilities::std_container_operations::DivideAndAssignToFirst(ContainerType&, const typenam
           e ContainerType::value_type::Type_&, const typename ContainerType::value_type::Type_&)':
  >> 62    /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-src/Sources/Utilities/std_container_operations.inc:
           199:96: error: cannot deduce template arguments for 'divides' from ()
     63       std::transform(container.begin(), container.end(), container.begin(), std::bind(std::divides(), std::placeholders::_1,
     64                                                                                                    ^
     65    Sources/Utilities/CMakeFiles/utilities.dir/build.make:92: recipe for target 'Sources/Utilities/CMakeFiles/utilities.dir/string_operations.
           cpp.o' failed
  >> 66    make[2]: *** [Sources/Utilities/CMakeFiles/utilities.dir/string_operations.cpp.o] Error 1
     67    make[2]: Leaving directory '/tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-build-xwh3dhv'
     68    CMakeFiles/Makefile2:355: recipe for target 'Sources/Utilities/CMakeFiles/utilities.dir/all' failed
  >> 69    make[1]: *** [Sources/Utilities/CMakeFiles/utilities.dir/all] Error 2
     70    make[1]: Leaving directory '/tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-build-xwh3dhv'
     71    Makefile:148: recipe for target 'all' failed
  >> 72    make: *** [all] Error 2

See build log for details:
  /tmp/tmn/spack-stage/spack-stage-splinelib-main-xwh3dhvr5bl72hmnchccqlii4v7qcx75/spack-build-out.txt
```

**Comment by kkCATS** [comment] 2021-07-20 13:53
Hi,

Unfortunately, this error is the result of a [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81486) within GCC that is only fixed for version 9 or later. Furthermore, SplineLib relies on C++17 standard library features like `std::transform_reduce`, which are only available from GCC version 9.3.

Therefore, you will need to install a more recent compiler supporting all C++17 functionalities. Since you are using spack, something like
```bash
$ spack install gcc@10  # install gcc at version 10
$ spack load gcc@10  # load installed gcc at version 10
$ spack compiler find  # let spack add gcc at version 10
$ spack install splinelib%gcc@10  # use gcc at version 10 to install splinelib
```
might work for you.

I will close this issue for now, as the issue is not with SplineLib.

**Closed as completed by kkCATS** 2021-07-20 13:53 UTC
